app/__init__.py
from flask import Flask


def create_app():
    app= Flask(__name__)
    app.config.from_mapping(
        DEBUG = True,
        SECRETE_KEY = 'dev',
        SQLALCHEMY_DATABASE_URI = "sqlite:///inventario.db"
    )


    from app.main import main_bp


    app.register_blueprint(main_bp)


    return app

app/main/__init__.py
from flask import Blueprint


main_bp = Blueprint('main', __name__, url_prefix='/')


from . import routes

app/main/routes.py
from flask import render_template, request
from app.main import main_bp


# Página principal
@main_bp.route('/')
def index():
    return render_template('main/index.html')



# Proyecto 1
@main_bp.route('/proyecto1')
def proyecto_1():
    return render_template('proyectos/api-rest.html')

app/templates/contacto.html
<section class="bg-light p-4" id="contacto">
    <div class="container">
        <div class="row align-items-center g-lg-5 py-5">
            <div class="col-lg-6 text-center text-lg-start">
                <h2 class="display-4 fw-bold 1h-1 mb-3" fw-bold 1h-1 mb-3>¡Hablemos!</h2>

                <p class="col-lg-10 fs-4">
                    Si deseas iniciar una conversación o tienes alguna consulta en mente, no dudes en ponerte en contacto conmigo. 
                    Puedes hacerlo de manera conveniente a través del formulario en línea o enviándome un correo electrónico.
                </p>
                <br>
                <p class="col-lg-10 fs-4">
                    Tu opinión es fundamental para mí, y estoy ansioso por escuchar lo que tienes que decir. Gracias por tomarte el 
                    tiempo de visitar mi sitio web y considerar trabajar juntos en futuras oportunidades."
                </p>

            </div>
            <div class="col-md-10 mx-auto col-lg-6">
                <form action="#" class="p-4 md-5 border rounded-3 bg-white" method="post">
                    <div class="mb-3">
                        <label for="name" class="form-label">Nombre</label>
                        <input type="text" class="form-control" id="name" name="name" required>
                    </div>
                    <div class="mb-3">
                        <label for="email" class="form-label">Correo electrónico</label>
                        <input type="email" class="form-control" id="email" name="email" required>
                    </div>
                    <div class="mb-3">
                        <label for="message" class="form-label">Mensaje</label>
                        <textarea class="form-control" id="message" name="message" rows="5" required></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary" style="width: 100%">Enviar</button>
                </form>
            </div>


        </div>
    </div>

</section>

app/templates/footer.html
<footer class="bg-dark p-5">
    <div class="container">
        <div class="row d-flex align-items-center">
            <div class="col-md-6">
                <h3 class="text-light">También puedes contactarme</h3>
                <p class="text-light">
                    Si tienes alguna pregunta o estás interesado en trabajar conmigo, no dudes en contactarme a través de mis redes sociales
                </p>
            </div>
            <div class="col-md-6">
                <h3 class="text-light mb-4 text-end">REDES SOCIALES</h3>
                <div class="d-flex justify-content-end">
                    <a href="" class="social-icon"><i class="fa-brands fa-x-twitter"></i></a>
                    <a href="" class="social-icon"><i class="fa-brands fa-square-github"></i></a>
                </div>
            </div>
        </div>

        <hr style="color:grey;">
        <div class="row mt-3">
            <div class="col-md-6">
                <p class="text-secondary">2023 Todos los derechos reservados.</p>
            </div>
            <div class="col-md-6">
                <p class="text-end text-secondary"> Hecho por Pablo Ramos Wilkins</p>
            </div>
        </div>
    </div>
</footer>

app/templates/home.html
<section class="bg-light" id="home">
    <div class="container col-xxl-8 px-4 py-5">
        <div class="row flex-lg-row-reverse align-items-center g-5 py-5">
            <div class="col-10 col-sm-8 col-lg-6">
                <img src="{{ url_for('static', filename='img/coder.jpg') }}" class="d-block mx-lg img-fluid" 
                height="500" width="500" alt="" loading="lazy">
            </div>
            <div class="col-lg-6">
                <h2 class="display-4">Hola, soy Pablo</h2>
                <p class="lead fs-3">Analista de Datos | Machine Learning | Desarrollador Web</p>
                <hr class="my-4">
                <p class="fs-5">En este sitio encontrarás mis proyectos recientes. ¡Gracias por visitarme!.</p>
                <a href="#proyectos" class="btn btn-primary btn-lg" role="button">Contáctame</a>
            </div>
        </div>
    </div>
</section>

app/templates/main/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/all.min.css') }}" rel="stylesheet">
    <script src="script.js"></script>

</head>
<body>
    
    {% block content %}
    <!-- Bloque de contenido -->
    {% endblock %}

    <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>

</body>
</html>

app/templates/main/contacto.html
<section class="bg-light p-4" id="contacto">
    <div class="container">
        <div class="row align-items-center g-lg-5 py-5">
            <div class="col-lg-6 text-center text-lg-start">
                <h2 class="display-4 fw-bold 1h-1 mb-3" fw-bold 1h-1 mb-3>¡Hablemos!</h2>

                <p class="col-lg-10 fs-4 fw-light">
                    Si deseas iniciar una conversación o tienes alguna consulta en mente, no dudes en ponerte en contacto conmigo. 
                    Puedes hacerlo de manera conveniente a través del formulario o enviándome un correo electrónico.
                </p>
                <br>
                <p class="col-lg-10 fs-4 fw-light">
                    Tu opinión es fundamental para mí, y estoy ansioso por escuchar lo que tienes que decir. Gracias por tomarte el 
                    tiempo de visitar mi sitio web y considerar trabajar juntos en futuras oportunidades."
                </p>

            </div>
            <div class="col-md-10 mx-auto col-lg-6">
                <form action="#" class="p-4 md-5 border rounded-3 bg-white" method="post">
                    <div class="mb-3">
                        <label for="name" class="form-label">Nombre</label>
                        <input type="text" class="form-control" id="name" name="name" required>
                    </div>
                    <div class="mb-3">
                        <label for="email" class="form-label">Correo electrónico</label>
                        <input type="email" class="form-control" id="email" name="email" required>
                    </div>
                    <div class="mb-3">
                        <label for="message" class="form-label">Mensaje</label>
                        <textarea class="form-control" id="message" name="message" rows="5" required></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary" style="width: 100%">Enviar</button>
                </form>
            </div>


        </div>
    </div>

</section>

app/templates/main/footer.html
<footer class="bg-dark p-5">
    <div class="container">
        <div class="row d-flex align-items-center">
            <div class="col-md-6">
                <h3 class="text-light">También puedes contactarme</h3>
                <p class="text-light fw-light">
                    Si tienes alguna pregunta o estás interesado en trabajar conmigo, no dudes en contactarme a través de mis redes sociales
                </p>
            </div>
            <div class="col-md-6">
                <h3 class="text-light mb-4 text-end">REDES SOCIALES</h3>
                <div class="d-flex justify-content-end">
                    <a href="" class="social-icon"><i class="fa-brands fa-x-twitter"></i></a>
                    <a href="https://github.com/PabloJRW" class="social-icon" target="_blank"><i class="fa-brands fa-square-github"></i></a>
                </div>
            </div>
        </div>

        <hr style="color:grey;">
        <div class="row mt-3">  
            <div class="col-md-6">
                <p class="text-secondary">© 2023 Todos los derechos reservados.</p>
            </div>
            <div class="col-md-6">
                <p class="text-end text-secondary"> Hecho por Pablo Ramos Wilkins</p>
            </div>
        </div>
    </div>
</footer>

app/templates/main/home.html
<section id="home" class="bg-body-tertiary">
    <div class="container col-xxl-8 px-4 py-5" id="intro">
        <div class="row flex-lg-row-reverse align-items-center g-5 py-5">
            <div class="col-10 col-sm-8 col-lg-6">
                <img src="{{ url_for('static', filename='img/coder.jpg') }}" class="d-block mx-lg img-fluid" 
                height="500" width="500" alt="" loading="lazy">
            </div>
            <div class="col-lg-6">

                <h2 class="display-4">Hola, soy Pablo</h2>
                <p class="lead fs-3">Análisis de Datos | Machine Learning | Desarrollo Web</p>
                
                <hr class="my-4">
                <p class="fs-5 fw-light">En este sitio encontrarás mis proyectos recientes.</p> 
                <p class="fs-5 fw-light">¡Gracias por visitarme!.</p>
                <a href="#proyectos" class="btn btn-primary btn-lg" role="button">Contáctame</a>
            </div>
        </div>
    </div>
</section>

app/templates/main/index.html
{% extends 'main/base.html' %}

{% block title %} Bienvenido! {% endblock %}

{% block content %}

<!-- Menú de navegación -->
{% include 'main/nav.html' %} 

<!-- Home-->
{% include 'main/home.html' %}

<!-- Sección de proyectos -->
{%include 'main/portafolio.html' %}

<!-- Sección de contacto -->
{% include 'main/contacto.html' %}

{% include 'main/footer.html' %}


{% endblock %}

app/templates/main/nav.html
<nav id="navbar" class="navbar navbar-expand-lg fixed-top bg-dark mb-5">
    <div class="container-fluid">
        <a class="navbar-brand" href="#"  style="color: white;">Pablo Ramos W.</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">          
            <ul class="navbar-nav ms-auto me-5">
                <li class="nav-item">
                    <a class="nav-link" href="#home" style="color: white;">Inicio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#portafolio" style="color: white;">Proyectos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#contacto" style="color: white;">Contacto</a>
                </li>
            </ul>    
        </div>
    </div>
</nav>

app/templates/main/portafolio.html
<section class="container p-5" id="portafolio">
    <h2 class="text-center">Mis Proyectos</h2>
    <hr class="mb-5">

    <div class="row row-cols-1 row-cols-md-3 g-4">

        <div class="col">
            <div class="card">
                <img src="{{ url_for('static', filename='img/proyectos/despliegue/app.png')}}" alt="" 
                class="d-block mx-lg-auto img-fluid">
                <div class="card-body bg-light">
                    <h5 class="card-title">Despliegue Modelo Machine Learning</h5>                                
                    <p class="card-text fw-light">Este proyecto implica el despliegue de una aplicación web que 
                        proporciona a los usuarios una interfaz gráfica intuitiva para ingresar variables 
                        que posteriormente son sometidas a un modelo de machine learning que realiza un análisis y devuelve una 
                        predicción basada en los parámetros proporcionados.</p>
                    <a href="{{ url_for('main.proyecto_1') }}" class="nav-link text-primary">Link aquí</a>
                </div>
            </div>
        </div>


        <div class="col">
            <div class="card">
                <img src="{{ url_for('static', filename='img/restapi.png')}}" alt="" 
                class="d-block mx-lg-auto img-fluid">
                <div class="card-body bg-light">
                    <img src="{{ url_for('static', filename='img/proyectos/api-rest/api.png')}}" alt="api_icon" height="25px" width="25px">
                    <h5 class="card-title">API REST</h5>                                
                    <p class="card-text fw-light">API REST que proporciona acceso a datos y funcionalidades 
                        a través de solicitudes HTTP. Utiliza estándares RESTful para la comunicación 
                        y ofrece una interfaz para interactuar con recursos, como obtener, crear, 
                        actualizar y eliminar datos de manera programática</p>
                    <a href="{{ url_for('main.proyecto_1') }}" class="nav-link text-primary">Link aquí</a>
                </div>
            </div>
        </div>

        <div class="col">
            <div class="card">
                <img src="{{ url_for('static', filename='img/proyectos/crud-flask/formulario.png')}}" alt="" 
                class="d-block mx-lg-auto img-fluid">
                <div class="card-body bg-light">
                    <h5 class="card-title">CRUD Web</h5>
                    <p class="card-text fw-light">CRUD web (Create, Read, Update, Delete) es una aplicación web que 
                        permite a los usuarios crear, leer, actualizar y eliminar datos en una base de datos. 
                        Esta aplicación proporciona una interfaz amigable que permite realizar estas operaciones 
                        básicas en los registros de la base de datos a través de una página web.</p>
                    <a href="#" class="nav-link text-primary">Link aquí</a>
                </div>
            </div>
        </div>

        <div class="col">
            <div class="card">
                <img src="{{ url_for('static', filename='img/3.jpg')}}" alt="" 
                class="d-block mx-lg-auto img-fluid">
                <div class="card-body bg-light">
                    <h5 class="card-title">Rest-API</h5>
                    <p class="card-text fw-light">Proyecto que consiste en una Restful API</p>
                    <a href="#" class="nav-link text-primary">Link aquí</a>
                </div>
            </div>
        </div>


    </div>
</section>

app/templates/proyectos/api-rest.html
{% extends 'proyectos/b_proyectos.html' %}

{% block title %} Proyectos - API REST {% endblock %}

{% block content %}

<section class="bg-light p-4">
    <div class="container col-xxl-8 px-4 py-5">
        <h1>API REST para la gestión de libros</h1>

        <p >En este proyecto, desarrollé una API REST que permite la gestión eficiente de una colección de libros. La API se diseñó
            teniendo en cuenta la interacción con aplicaciones front-end, sistemas de gestión de bases datos y usuarios finales. Proporciona 
            funcionalidades para crear, leer, actualizar y eliminar resgistros de libros, lo que lo convierte en una herramienta valiosa para 
            bibliotecas, librerías en linea y entusuastas de la lectura.
        </p>
    </div>

</section>


{% endblock %}

app/templates/proyectos/b_proyectos.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/all.min.css') }}" rel="stylesheet">

</head>
<body>

    {%include 'proyectos/nav.html' %}
    
    {% block content %}
    <!-- Bloque de contenido -->
    {% endblock %}

    <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>

</body>
</html>

app/templates/proyectos/nav.html
<nav id="navbar" class="navbar navbar-expand-lg fixed-top bg-dark mb-5">
    <div class="container-fluid">
        <a class="navbar-brand" href="/pablo"  style="color: white;">Regresar</a>
    </div>
</nav>